#!/bin/sh



appname="$1"
if [ "$appname" = "" ]; then
    appname="Passenger-3.0.11"
fi

user="$2"
if [ "$user" = "" ]; then
    user="501"
fi

pattern="\/Software\/${appname}"
destination="\/Users\/${user}\/Apps\/Passenger"

echo "AppName: ${appname}"
echo "Pattern: ${pattern}"
echo "Destination: ${destination}"
files="
lib/ruby/1.9.1/x86_64-freebsd9.0/rbconfig.rb
bin/gem
bin/rake
bin/bundle
bin/irb
bin/erb
bin/rdoc
bin/ri
bin/testrb
bin/xml2-config
bin/ncursesw5-config
bin/curl-config
lib/pkgconfig/zlib.pc
lib/pkgconfig/libxml-2.0.pc
lib/pkgconfig/libcurl.pc
lib/libxml2.la
lib/xml2Conf.sh
lib/libyaml.la
lib/libcharset.la
lib/libcharset.la
lib/libiconv.la
lib/libcurl.la
conf/nginx.conf
include/ruby-1.9.1/x86_64-freebsd9.0/ruby/config.h
"

for i in $files; do
    echo "Processing file: $i"
    cp "${i}" "${i}.tmp"
    sed "s/${pattern}/${destination}/g" "${i}.tmp" > "${i}"
    rm "${i}.tmp"
done
