#!/bin/sh

VERSION="0.1.7"

SCRIPT_ROOT="/opt/SvdOpt/"
SOFTWARE_DIR="/Software/"
TMP_ROOT="/tmp/SvdOpt/"
DEFINITIONS_DIR="${SCRIPT_ROOT}definitions/"
DEFAULTS="${DEFINITIONS_DIR}defaults.def"
APPLICATIONS_NAME_LIST="${DEFINITIONS_DIR}applications"
LIBRARIES_NAME_LIST="${DEFINITIONS_DIR}libraries"
LOG="${SOFTWARE_DIR}INSTALL_LOG"
DEFAULT_PATH="/bin:/usr/bin:/sbin:/usr/sbin"

# DEBUG="true"

PATCH_BIN="/usr/bin/patch"
LN_BIN="/bin/ln"
DATE_BIN="/bin/date"
SED_BIN="/usr/bin/sed"
CUT_BIN="/usr/bin/cut"
TR_BIN="/usr/bin/tr"
LS_BIN="/bin/ls"
CAT_BIN="/bin/cat"
RM_BIN="/bin/rm"
MKDIR_BIN="/bin/mkdir"
UNAME_BIN="/usr/bin/uname"
TOUCH_BIN="/usr/bin/touch"
TAR_BIN="/usr/bin/tar"
ID_BIN="/usr/bin/id"
GREP_BIN="/usr/bin/grep"
LDCONFIG_BIN="/sbin/ldconfig"
TAIL_BIN="/usr/bin/tail"
FETCH_BIN="/usr/bin/fetch"

if [ `$UNAME_BIN` = "Darwin" ]; then
FETCH_BIN="/usr/bin/curl -L -O"
fi