#!/bin/sh

# NOTE: STABLE -> export PACKAGESITE='http://ftp.freebsd.org/pub/FreeBSD/ports/amd64/packages-stable/Latest/'
export PACKAGESITE='http://ftp.freebsd.org/pub/FreeBSD/ports/amd64/packages-9-current/'

VERSION="0.5.0"

# DEBUG="true"

MAIN_SOURCE_REPOSITORY="http://software.verknowsys.com/"
HOST_NODE_NAME="grunt-$(/sbin/sha1 -qs \\"`date`\\")"
DEFAULT_PATH="/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
SNAPSHOT_NAME="clang_fbsd64_9_basesystem_snapshot"
SNAPSHOT_ROOT="/opt/clang_root"
DFS_MOUNT_POINT="/dfs"
DFS_CACHE_DIR="/var/dfs/cache"
SCRIPT_ROOT="/opt/SvdOpt/"
SOFTWARE_DIR="/Software/"
TMP_ROOT="/var/SvdOpt/"
DEFAULT_SSH_PORT="60022"
SYSUSERS="dmilith teamon"
SYSGROUP="wheel"
SERVICES="pf ntpd sshd syslogd"
KERNEL_CONFIG="VERKNOWSYS"
BOOT_LOADER_CONFIG="/boot/loader.conf"
RC_CONF_FILE="/etc/rc.conf"
DEFINITIONS_DIR="${SCRIPT_ROOT}definitions/"
DEFAULTS="${DEFINITIONS_DIR}defaults.def"
LOG="${SOFTWARE_DIR}INSTALL_LOG"
PREFILES="${SCRIPT_ROOT}prefiles/etc/"
DINSTAPP="$(pwd)/SOFTWARE-INSTALLER"
SYSTEM_GET_SHELL_PATH="$DINSTAPP getshellpath"
SYSTEM_GET_SHELL_LDLIB="$DINSTAPP getshellld"
KERNELBUILDAPP="$(pwd)/GRUNT-KERNEL-BUILD"

FREEBSDUPDATE_BIN="/usr/sbin/freebsd-update"
PORTSNAP_BIN="/usr/sbin/portsnap"
CSUP_BIN="/usr/bin/csup"
BSDMAKE_BIN="/usr/bin/make"
NEXTBOOT_BIN="/sbin/nextboot"
PKG_ADD_BIN="/usr/sbin/pkg_add"
KLDLOAD_BIN="/sbin/kldload"
SERVICE_BIN="/usr/sbin/service"
PATCH_BIN="/usr/bin/patch"
PW_BIN="/usr/sbin/pw"
CP_BIN="/bin/cp"
LN_BIN="/bin/ln"
DATE_BIN="/bin/date"
SED_BIN="/usr/bin/sed"
CUT_BIN="/usr/bin/cut"
TR_BIN="/usr/bin/tr"
LS_BIN="/bin/ls"
CAT_BIN="/bin/cat"
RM_BIN="/bin/rm"
MKDIR_BIN="/bin/mkdir"
UNAME_BIN="/usr/bin/uname"
TOUCH_BIN="/usr/bin/touch"
TAR_BIN="/usr/bin/tar"
ID_BIN="/usr/bin/id"
GREP_BIN="/usr/bin/grep"
IFCONFIG_BIN="/sbin/ifconfig"
LDCONFIG_BIN="/sbin/ldconfig"
TAIL_BIN="/usr/bin/tail"
FETCH_BIN="/usr/bin/fetch"
CHMOD_BIN="/bin/chmod"
CHOWN_BIN="/usr/sbin/chown"
FIND_BIN="/usr/bin/find"
TOUCH_BIN="/usr/bin/touch"
PWD_MKDB_BIN="/usr/sbin/pwd_mkdb"
MKTEMP_BIN="/usr/bin/mktemp"
BASENAME_BIN="/usr/bin/basename"
TZSETUP_BIN="/usr/sbin/tzsetup"

if [ $($UNAME_BIN) = "Darwin" ]; then
FETCH_BIN="/usr/bin/curl -L -O"
fi


# helpers:

note () {
    echo " INFO: $1"
}


debug () {
    if [ ! "$DEBUG" = "" ]; then
        echo "DEBUG: $1"
    fi
}


error () {
    echo "ERROR: $1"
}


# quick hashmap implementation
export mapdir=$($MKTEMP_BIN -dt $($BASENAME_BIN $0))


put () {
  [ "$#" != 3 ] && exit 1
  mapname=$1; key=$2; value=$3
  [ -d "${mapdir}/${mapname}" ] || $MKDIR_BIN "${mapdir}/${mapname}"
  echo $value >"${mapdir}/${mapname}/${key}"
}


get () {
  [ "$#" != 2 ] && exit 1
  mapname=$1; key=$2
  $CAT_BIN "${mapdir}/${mapname}/${key}"
}


trap "rm -r ${mapdir}" EXIT

put "SYSUSERS" "dmilith" "666"
put "SYSUSERS" "teamon" "1337"
