#!/bin/sh

. $(pwd)/config

if [ ! -e "${SOFTWARE_DIR}" ]; then
    error "Unable to find software directory: ${SOFTWARE_DIR}. Try to run GRUNT-POST-BASE-INSTALLER first"
    exit
fi


postfix=".tar.gz"

cd "${SOFTWARE_DIR}"
$RM_BIN -vf "*${postfix}"
for element in *; do
    if [ -d $element ]; then
        if [ ! -L $element ]; then
            note "Preparing archive of: $element"
            $TAR_BIN cf ${element}${postfix} ./${element}
            note "Sending archive to remote: ${MAIN_BINARY_REPOSITORY_DESTINATION}"
            $SCP_BIN "${element}${postfix}" "${MAIN_BINARY_REPOSITORY_DESTINATION}${element}${postfix}"
        fi
    fi
done


# note "Creating software index for current architecture"

note "Done"
exit
