#!/bin/sh

if [ ! -e $(pwd)/config ]; then
    error "Unable to find config: $(pwd)/config"
    exit
fi
. $(pwd)/config

note "Please make sure that system has updated kernel sources. Run $(ls GRUNT-POST-*) script before executing this one!"

if [ ! "$SYSTEM_NAME" = "FreeBSD" ]; then
    note "This script is designed to be executed on FreeBSD 8.x systems only."
    exit 1
fi

if [ ! -e "/usr/src/sys" ]; then
    note "Use sysinstall first and install BSD kernel sources"
    exit 1
fi

note "Fetching FreeBSD sources for development server (grunt)"
$CSUP_BIN /etc/csup.grunt

note "Updating FreeBSD release and sources"
$FREEBSDUPDATE_BIN fetch >> $LOG
$FREEBSDUPDATE_BIN install >> $LOG

note "Linking $KERNEL_CONFIG kernel config"
$RM_BIN "/usr/src/sys/${SYSTEM_ARCH}/conf/${KERNEL_CONFIG}"
$LN_BIN -s "$(pwd)/${KERNEL_CONFIG}" "/usr/src/sys/${SYSTEM_ARCH}/conf/${KERNEL_CONFIG}"


MTREE_PATH="/opt/src/etc/mtree/"

cd /usr/src
$MKDIR_BIN -p "${SNAPSHOT_ROOT}"

/bin/chflags -R 0 "${SNAPSHOT_ROOT}" && \
$RM_BIN -rf "${SNAPSHOT_ROOT}" && \
$BSDMAKE_BIN -j2 buildworld && \
$CP_BIN rv "${SCRIPT_ROOT}prefiles/${MTREE_PATH}BSD.var.dist" "${MTREE_PATH}" && \
$CP_BIN rv "${SCRIPT_ROOT}prefiles/${MTREE_PATH}BSD.usr.dist" "${MTREE_PATH}" && \
$CP_BIN rv "${SCRIPT_ROOT}prefiles/${MTREE_PATH}BIND.chroot.dist" "${MTREE_PATH}" && \
$BSDMAKE_BIN installworld DESTDIR="${SNAPSHOT_ROOT}" && \
$TAR_BIN cfv "/opt/${SNAPSHOT_NAME}.tar.gz" "${SNAPSHOT_ROOT}"
note "Done"

exit
