#!/bin/sh

if [ ! -e $(pwd)/config ]; then
    error "Unable to find config: $(pwd)/config"
    exit
fi
. $(pwd)/config

if [ ! "$SYSTEM_NAME" = "FreeBSD" ]; then
    note "This script is designed to be executed on FreeBSD 8.x systems only."
    exit 1
fi


kernel="kernel.tar.gz"
base="${SNAPSHOT_ROOT}"

cd ${OPTDIR}
if [ ! -e "${OPTDIR}${kernel}" ]; then # HACK
    $FETCH_BIN $MAIN_SOURCE_REPOSITORY/${kernel}
fi

if [ ! -e "${OPTDIR}${base}" ]; then # HACK
    $FETCH_BIN $MAIN_SOURCE_REPOSITORY/${base}
fi

if [ ! -d "${OPTDIR}clang_root" ]; then
    $TAR_BIN xf ${base}
fi


cd /

RMLIST="/lib /libexec /bin /boot /usr /sbin"
for i in ${RMLIST}; do
    note "Removing block flag on file: ${i}"
    /rescue/chflags -R 0 ${i}
done

for i in ${RMLIST}; do
   note "Removing: ${i}"
   /rescue/rm -rf "${i}"
   note "Installing: ${i}"
   /rescue/cp -r /opt/clang_root${i} /
done

cd /boot

/bin/chflags -R 0 /rescue
$RM_BIN -rf /rescue
$CP_BIN -r /opt/clang_root/rescue /

cd /boot
note "Installing kernel binary"
/rescue/tar xf /opt/${kernel}

note "Preparing src and obj links"
$RM_BIN -rf /usr/src
$RM_BIN -rf /usr/obj
$LN_BIN -s /opt/obj /usr/obj
$LN_BIN -s /opt/src /usr/src

note "Done"
exit
