#!/bin/sh

if [ ! -e $(pwd)/config ]; then
    error "Unable to find config: $(pwd)/config"
    exit
fi
. $(pwd)/config

note "Please make sure that system has updated kernel sources. Run $(ls GRUNT-POST-*) script before executing this one!"

if [ ! "$SYSTEM_NAME" = "FreeBSD" ]; then
    note "This script is designed to be executed on FreeBSD systems only."
    exit 1
fi

# First copy prefiles to destination directory (includes freebsd-update, src & make configurations, which must be ready before building kernel)
$MKDIR_BIN -p "$SOFTWARE_DIR"
note "Copying ${PREFILES} to /etc"
$CP_BIN -r "${PREFILES}" /etc

note "Fetching FreeBSD sources for development server (grunt)"
$CSUP_BIN /etc/csup.grunt

note "Updating FreeBSD release and sources"
$FREEBSDUPDATE_BIN fetch >> $LOG
$FREEBSDUPDATE_BIN install >> $LOG

note "Linking $KERNEL_CONFIG kernel config"
$RM_BIN "/usr/src/sys/amd64/conf/${KERNEL_CONFIG}"
$LN_BIN -s "$(pwd)/${KERNEL_CONFIG}" /usr/src/sys/amd64/conf/${KERNEL_CONFIG}

cd /usr/src
$BSDMAKE_BIN cleandir >> $LOG
$BSDMAKE_BIN -j2 buildkernel KERNCONF=$KERNEL_CONFIG && \
$BSDMAKE_BIN installkernel KERNCONF=$KERNEL_CONFIG && \
note "Done"

# note "Enabling some additional options in $BOOT_LOADER_CONF"
# echo 'vfs.zfs.prefetch_disable="1"' >> $BOOT_LOADER_CONF
# echo 'vfs.zfs.txg.timeout="5"' >> $BOOT_LOADER_CONF
# echo 'vfs.zfs.zil_disable="0"' >> $BOOT_LOADER_CONF

exit
