#!/bin/sh

. "lib/config"
. "lib/helpers"

if [ ! "$SYSTEM_NAME" = "FreeBSD" ]; then
    note "This script is designed to be executed on FreeBSD 8.x systems only."
    exit 1
fi

$MKDIR_BIN ${OPTDIR} > /dev/null
note "Getting OpenJDK"
cd ${OPTDIR}
$FETCH_BIN "${MAIN_BINARY_REPOSITORY}/common/${OPENJDK7_FBSD9_32BIT_BUILD_NAME}"
$TAR_BIN xf "${OPENJDK7_FBSD9_32BIT_BUILD_NAME}"
export JAVA_HOME="${OPTDIR}/openjdk7"

RMLIST="/usr/libexec/sendmail /mnt /proc /srv /cdrom /root /home /COPYRIGHT /etc/bluetooth /etc/rc.d/sendmail /etc/mail /etc/X11 /etc/csh.* /etc/ftpusers /etc/hosts.lpd /etc/mail.rc /usr/sbin/sendmail /usr/bin/mail /var/mail"

for i in ${RMLIST}; do
   debug "Removing: $i"
   $RM_BIN -rf "$i"
done

note "Copying ${PREFILES} to /etc"
$CP_BIN -r "${PREFILES}" /etc

note "Some touches and removes from beginning. Shot first, questions later."
$TOUCH_BIN /var/log/console.log
$RM_BIN -rf /usr/home
$MKDIR_BIN -p /usr/root
# $RM_BIN -rf /boot/kernel.* # remove old kernels

note "Filling additional configurations"
echo "hostname=\"$HOST_NODE_NAME\"" >> $RC_CONF_FILE

note "Setting network interfaces.."
for interface in $($IFCONFIG_BIN -l); do
    if [ ! "$interface" = "lo0" ]; then
        echo "ifconfig_${interface}=\"DHCP\"" >> $RC_CONF_FILE
    fi
done

note "Updating passwd cache database"
$PWD_MKDB_BIN -p /etc/master.passwd

note "Installing base in ${SOFTWARE_DIR}"
$DINSTAPP lists/base

note "Setting PATH & LDDIR"
echo "$($SYSTEM_GET_SHELL_PATH):$JAVA_HOME" >> /etc/profile
echo "" >> /etc/profile
echo $($SYSTEM_GET_SHELL_LDLIB) >> /etc/profile
echo "" >> /etc/profile
. /etc/profile

note "Setting zshrc to autoload profile"
echo "source /etc/profile" >> /etc/zshrc

note "Updating shells"
echo "$(which zsh)" >> /etc/shells

note "Adding default users"
for user in $SYSUSERS; do
    if [ ! -d /usr/home/${user} ]; then
        $MKDIR_BIN -p /usr/home/${user}
    fi
    $PW_BIN useradd $user -u $(get "SYSUSERS" "${user}") -d /usr/home/${user} -g $SYSGROUP -s "$(which zsh)"
    $TOUCH_BIN /usr/home/${user}/.zshrc
    $CHOWN_BIN -R ${user}:$SYSGROUP /usr/home/${user}
done

note "Updating ssh config"
echo "" >> /etc/ssh/ssh_config
echo "Host verknowsys.com git.verknowsys.com" >> /etc/ssh/ssh_config
echo "Port $DEFAULT_SSH_PORT" >> /etc/ssh/ssh_config

# note "Syncing to NTP server"
# $NTPDATE_BIN ${NFS_FIRST_FETCH}

note "Restarting system services"
for service in ${SERVICES}; do
    note "$service"
    service $service restart 2>> $LOG >> $LOG &
done

note "Getting ServeD from git repository"
cd ${TMP_ROOT}
if [ -d ${TMP_ROOT}/ServeD ]; then
    cd ${TMP_ROOT}/ServeD
    git pull origin master
    $CP_BIN -r ${TMP_ROOT}/ServeD ${OPTDIR}
else
    git clone ssh://tunemates@git.verknowsys.com/git/ServeD.git
    $CP_BIN -r ${TMP_ROOT}/ServeD ${OPTDIR}
fi

note "Building ServeD"
cd ${OPTDIR}/ServeD
bin/sbt compile

# note "Setting time zone"
# $TZSETUP_BIN

note "Done"
exit
