#!/bin/sh

if [ ! -e $(pwd)/config ]; then
    error "Unable to find config: $(pwd)/config"
    exit
fi
. $(pwd)/config

if [ ! "$($UNAME_BIN)" = "FreeBSD" ]; then
    note "This script is designed to be executed on FreeBSD 8.x systems only."
    exit 1
fi

RMLIST="/media /mnt /proc /srv /cdrom /root /home /COPYRIGHT /etc/bluetooth /etc/rc.d/sendmail /etc/mail /etc/ntp /etc/ppp /etc/skel /etc/X11 /etc/csh.* /etc/ftpusers /etc/hosts.lpd /etc/mail.rc /usr/sbin/sendmail /usr/bin/mail /var/mail"

for i in ${RMLIST}; do
   debug "Removing: $i"
   $RM_BIN -rf "$i"
done

# First copy prefiles to destination directory (includes freebsd-update, src & make configurations, which must be ready before building kernel)
note "Copying ${PREFILES} to /etc"
$CP_BIN -r "${PREFILES}" /etc

note "Fetching FreeBSD sources for development server (grunt)"
$CSUP_BIN /etc/csup.grunt

note "Updating FreeBSD release with sources"
$FREEBSDUPDATE_BIN fetch >> $LOG
$FREEBSDUPDATE_BIN install >> $LOG

note "Some touches and removes from beginning. Shot first, questions later."
$TOUCH_BIN /var/log/console.log
$RM_BIN -rf /usr/home
$MKDIR_BIN -p /usr/root

note "Filling additional configurations"
echo "hostname=\"$HOST_NODE_NAME\"" >> $RC_CONF_FILE

note "Setting interfaces.."
for interface in $($IFCONFIG_BIN -l); do
    if [ ! "$interface" = "lo0" ]; then
        echo "ifconfig_${interface}=\"DHCP\"" >> $RC_CONF_FILE
    fi
done

note "Updating passwd cache database"
$PWD_MKDB_BIN -p /etc/master.passwd

note "Installing base in ${SOFTWARE_DIR}"
$DINSTAPP lists/base

note "Setting PATH & LDDIR"
echo $($SYSTEM_GET_SHELL_PATH) >> /etc/profile
echo "" >> /etc/profile
echo $($SYSTEM_GET_SHELL_LDLIB) >> /etc/profile
echo "" >> /etc/profile
. /etc/profile

note "Setting zshrc to autoload profile"
echo "source /etc/profile" >> /etc/zshrc

note "Updating shells"
echo "$(which zsh)" >> /etc/shells

note "Adding default users"
for user in $SYSUSERS; do
    if [ ! -d /usr/home/${user} ]; then
        $MKDIR_BIN -p /usr/home/${user}
    fi
    $PW_BIN useradd $user -u $(get "SYSUSERS" "${user}") -d /usr/home/${user} -g $SYSGROUP -s "$(which zsh)"
    $TOUCH_BIN /usr/home/${user}/.zshrc
    $CHOWN_BIN -R ${user}:$SYSGROUP /usr/home/${user}
done

note "Updating ssh config"
echo "" >> /etc/ssh/ssh_config
echo "Host verknowsys.com git.verknowsys.com fiend.pl" >> /etc/ssh/ssh_config
echo "Port $DEFAULT_SSH_PORT" >> /etc/ssh/ssh_config

# note "Syncing to NTP server"
# $NTPDATE_BIN ${NFS_FIRST_FETCH}

note "Restarting system services"
for service in ${SERVICES}; do
    service $service restart 2>> $LOG >> $LOG &
done

note "Getting ServeD from git repository"
cd ${TMP_ROOT}
if [ -d ${TMP_ROOT}/ServeD ]; then
    cd ${TMP_ROOT}/ServeD
    git pull origin master
    $CP_BIN -r ${TMP_ROOT}/ServeD /opt
else
    git clone ssh://tunemates@git.verknowsys.com/git/ServeD.git
    $CP_BIN -r ${TMP_ROOT}/ServeD /opt
fi

note "Building ServeD"
cd /opt/ServeD
sbt update
sbt compile

note "Installing required native libraries for OpenJDK" # XXX: hardcoded
$CP_BIN /opt/ServeD/libs.native.64/FreeBSD_8_1/libsigar-amd64-freebsd-8.so /Software/Openjdk-1.6.0-b22/jre/lib/amd64/

# note "Setting time zone"
# $TZSETUP_BIN

note "Done"
exit
