#!/bin/sh

if [ ! -e $(pwd)/config ]; then
    error "Unable to find config: $(pwd)/config"
    exit
fi
. $(pwd)/config

note "Please make sure that system has updated kernel sources. Run $(ls GRUNT-POST-*) script before executing this one!"

if [ ! "$($UNAME_BIN)" = "FreeBSD" ]; then
    note "This script is designed to be executed on FreeBSD 8.x systems only."
    exit 1
fi

if [ ! -e "/usr/src/sys" ]; then
    note "Use sysinstall first and install BSD kernel sources"
    exit 1
fi

note "Linking $KERNEL_CONFIG kernel config"
$RM_BIN "/usr/src/sys/amd64/conf/${KERNEL_CONFIG}"
$LN_BIN -s "$(pwd)/${KERNEL_CONFIG}" /usr/src/sys/amd64/conf/${KERNEL_CONFIG}


MTREE_PATH="/opt/src/etc/mtree/"

cd /usr/src
$MKDIR_BIN -p /opt/clang_root

/bin/chflags -R 0 /opt/clang_root && \
$RM_BIN -rf /opt/clang_root && \
$BSDMAKE_BIN buildworld && \
$CP_BIN rvf ${SCRIPT_ROOT}prefiles/${MTREE_PATH}BSD.var.dist "${MTREE_PATH}" && \
$CP_BIN rvf ${SCRIPT_ROOT}prefiles/${MTREE_PATH}BSD.usr.dist "${MTREE_PATH}" && \
$CP_BIN rvf ${SCRIPT_ROOT}prefiles/${MTREE_PATH}BIND.chroot.dist "${MTREE_PATH}" && \
$BSDMAKE_BIN installworld DESTDIR=/opt/clang_root && \
note "Done"

exit
