#!/bin/sh

if [ ! -e $(pwd)/config ]; then
    error "Unable to find config: $(pwd)/config"
    exit
fi
. $(pwd)/config

note "Please make sure that system has updated kernel sources. Run $(ls GRUNT-POST-*) script before executing this one!"

if [ ! "$($UNAME_BIN)" = "FreeBSD" ]; then
    note "This script is designed to be executed on FreeBSD 8.x systems only."
    exit 1
fi

if [ ! -e "/usr/src/sys" ]; then
    note "Use sysinstall first and install BSD kernel sources"
    exit 1
fi

note "Linking $KERNEL_CONFIG kernel config"
$RM_BIN "/usr/src/sys/amd64/conf/${KERNEL_CONFIG}"
$LN_BIN -s "$(pwd)/${KERNEL_CONFIG}" /usr/src/sys/amd64/conf/${KERNEL_CONFIG}

cd /usr/src
$BSDMAKE_BIN cleandir
$BSDMAKE_BIN buildkernel KERNCONF=$KERNEL_CONFIG && \
$BSDMAKE_BIN installkernel KERNCONF=$KERNEL_CONFIG && \
note "Done"

# $BSDMAKE_BIN buildworld && \
# mergemaster -p && \
# $BSDMAKE_BIN installworld && \

exit
