#!/bin/sh
# @author: Daniel (dmilith) Dettlaff (dmilith@verknowsys.com)


# load configuration from sofin.conf
CONF_FILE="./sofin.conf.sh"
if [ -e "${CONF_FILE}" ]; then
    . "${CONF_FILE}"
else
    echo "FATAL: No configuration file found: ${CONF_FILE}"
    exit 1
fi


install_base () {
    ${RM_BIN} -rf "/usr/bin/sofin"
    ${LN_BIN} -s "$($PWD_BIN)/sofin" /usr/bin/sofin
    check_command_result $?

    ${RM_BIN} -rf "/etc/${CONF_FILE}"
    ${LN_BIN} -s "$($PWD_BIN)/${CONF_FILE}" "/etc/${CONF_FILE}"
    check_command_result $?

    ${MKDIR_BIN} -p /Software/.cache
    note "Installation succeeded."
}


note "${SYSTEM_NAME} installation"
case "${SYSTEM_NAME}" in

  Darwin)
    if [ ! -e "${HOME}/.profile" ]; then
      ${LN_BIN} -s "/Users/$(${ID_BIN} -u)/.profile" "${HOME}/.profile"
      check_command_result $?
    fi
    install_base
    ;;

  FreeBSD|Linux)
    check_root
    install_base
    ;;

  *)
    echo "No supported architecture found"
    ;;

esac
