#!/bin/sh


readonly CONF_FILE="/etc/sofin.conf.sh"
if [ -e "${CONF_FILE}" ]; then
    . "${CONF_FILE}"
    validate_env
else
    echo "FATAL: No configuration file found: ${CONF_FILE}. Sofin isn't installed properly."
    exit 1
fi

note "Upload enabled for: $1"

postfix=".tar.gz"

note "Changing dir to: ${SOFTWARE_DIR}"
cd "${SOFTWARE_DIR}"
#$RM_BIN -vf "*${postfix}"
for element in $*; do
    if [ -d "${element}" ]; then
        if [ ! -L "${element}" ]; then
            lowercase_element="$(${PRINTF_BIN} "${element}" | ${TR_BIN} '[A-Z]' '[a-z]')"
            version_element="$(cat ${element}/${lowercase_element}.installed)"
            name="${element}-${version_element}${postfix}"
            note "Preparing archive of: ${name}"
            if [ ! -e "./${name}" ]; then
                ${TAR_BIN} zcf "${name}" "./${element}"
            else
                note "Archive already exists. Skipping: ${name}"
            fi

            case "${SYSTEM_NAME}" in
                Darwin|Linux)
                    export archive_sha1="$(${SHA_BIN} "${name}" | ${AWK_BIN} '{ print $1 }')"
                    ;;

                FreeBSD)
                    export archive_sha1="$(${SHA_BIN} -q "${name}")"
                    ;;
            esac

            ${PRINTF_BIN} "${archive_sha1}" > "${name}.sha1"
            note "Archive sha: ${archive_sha1}"
            note "Sending archive to remote: ${MAIN_BINARY_REPOSITORY_DESTINATION}"
            ${SCP_BIN} "${name}" "${MAIN_BINARY_REPOSITORY_DESTINATION}${name}"
            ${SCP_BIN} "${name}.sha1" "${MAIN_BINARY_REPOSITORY_DESTINATION}${name}.sha1"
            ${RM_BIN} -f "${name}"
            ${RM_BIN} -f "${name}.sha1"
        fi
    else
        warn "Not found software named: ${element}!"
    fi
done


note "Done"
exit
