#!/bin/sh

. ./config

RMLIST="/media /mnt /COPYRIGHT /etc/bluetooth /etc/mail /etc/ntp /etc/ppp /etc/skel /etc/X11 /etc/csh.* /etc/ftpusers /etc/hosts.lpd /etc/mail.rc /usr/sbin/sendmail /usr/bin/mail /var/mail"

for i in ${RMLIST}; do
   echo "Removing: $i"
   $RM_BIN -rf "$i"
done


echo "Copying ${PREFILES} to /etc"
$CP_BIN -r ${PREFILES} /etc

echo "Filling additional configurations"
echo "Enter hostname:"
read HOSTNAME
echo "hostname=\"$HOSTNAME\"" >> $RC_CONF_FILE

echo "Setting interfaces.."
for interface in $($IFCONFIG_BIN -l); do
    if [ ! "$interface" = "lo0" ]; then
        echo "ifconfig_${interface}=\"DHCP\"" >> $RC_CONF_FILE
    fi
done


echo "Updating passwd cache database"
$PWD_MKDB_BIN -p /etc/master.passwd

echo "Updating FreeBSD release"
$FREEBSDUPDATE_BIN fetch
$FREEBSDUPDATE_BIN install

echo "Restarting services"
service pf restart
service sshd restart

