--- Makefile.orig	2012-12-02 00:48:29.000000000 +0100
+++ Makefile	2012-12-02 00:48:37.000000000 +0100
@@ -19,7 +19,7 @@
 CFLAGS = -w -verbose -fast -std1 -g0
 
 # For GNU C compiler
-CFLAGS = -Wall -O6 # -pedantic
+CFLAGS = -Wall -Os # -pedantic
 
 SHELL = /bin/sh
 
