#!/bin/sh

# LD_LIBRARY_PATH on linux: /lib/ld-2.11.2.so --library-path /Software/Git-1.7.5/lib /Software/Git-1.7.5/bin/git

#export PACKAGESITE='http://ftp.freebsd.org/pub/FreeBSD/ports/amd64/packages-stable/Latest/'
# NOTE: 9.0 ->
export PACKAGESITE='http://ftp.freebsd.org/pub/FreeBSD/ports/amd64/packages-9-current/'

VERSION="0.8.0"

#DEBUG="true"

FREEBSDUPDATE_BIN="/usr/sbin/freebsd-update"
PORTSNAP_BIN="/usr/sbin/portsnap"
CSUP_BIN="/usr/bin/csup"
BSDMAKE_BIN="/usr/bin/make"
NEXTBOOT_BIN="/sbin/nextboot"
PKG_ADD_BIN="/usr/sbin/pkg_add"
KLDLOAD_BIN="/sbin/kldload"
SERVICE_BIN="/usr/sbin/service"
PATCH_BIN="/usr/bin/patch"
PW_BIN="/usr/sbin/pw"
CP_BIN="/bin/cp"
LN_BIN="/bin/ln"
DATE_BIN="/bin/date"
SED_BIN="/usr/bin/sed"
CUT_BIN="/usr/bin/cut"
TR_BIN="/usr/bin/tr"
LS_BIN="/bin/ls"
CAT_BIN="/bin/cat"
RM_BIN="/bin/rm"
MKDIR_BIN="/bin/mkdir"
TOUCH_BIN="/usr/bin/touch"
TAR_BIN="/usr/bin/tar"
ID_BIN="/usr/bin/id"
GREP_BIN="/usr/bin/grep"
IFCONFIG_BIN="/sbin/ifconfig"
LDCONFIG_BIN="/sbin/ldconfig"
TAIL_BIN="/usr/bin/tail"
CHMOD_BIN="/bin/chmod"
CHOWN_BIN="/usr/sbin/chown"
FIND_BIN="/usr/bin/find"
TOUCH_BIN="/usr/bin/touch"
PWD_MKDB_BIN="/usr/sbin/pwd_mkdb"
MKTEMP_BIN="/usr/bin/mktemp"
BASENAME_BIN="/usr/bin/basename"
TZSETUP_BIN="/usr/sbin/tzsetup"
FETCH_BIN="/usr/bin/fetch"
SCP_BIN="/usr/bin/scp"
UNAME_BIN="/usr/bin/uname"

OPTDIR="/opt/"
CONFDIR="/etc/"
SYSUSERS="dmilith teamon"
SYSGROUP="staff"
SERVICES="pf sshd syslogd"
DEFAULT_SSH_PORT="60022"
KERNEL_CONFIG="VERKNOWSYS"
SOFTWARE_DIR="/Software/"
HOME_DIR="/Users/"
HOME_APPS_DIR="Apps/"
TMP_ROOT="/var/SvdOpt/"
RC_CONF_FILE="/etc/rc.conf"

OPENJDK7_FBSD9_32BIT_BUILD_NAME="openjdk7_fbsd9.tar.gz"
SYSTEM_ARCH="64"
SYSTEM_VERSION=$($UNAME_BIN -r)
SYSTEM_NAME=$($UNAME_BIN)
MAIN_SOURCE_REPOSITORY="http://software.verknowsys.com/source/"
MAIN_BINARY_REPOSITORY_DESTINATION="dmilith@verknowsys.com:/opt/software/binary/${SYSTEM_NAME}/${SYSTEM_ARCH}/${SYSTEM_VERSION}/"
MAIN_BINARY_REPOSITORY="http://software.verknowsys.com/binary/${SYSTEM_NAME}/${SYSTEM_ARCH}/${SYSTEM_VERSION}"
HOST_NODE_NAME="drahk-grunt" #-$(/sbin/sha1 -qs \\"`date`\\")"
DEFAULT_PATH="/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
SNAPSHOT_NAME="clang_fbsd64_9_basesystem_snapshot"
SNAPSHOT_ROOT="$OPTDIR/clang_root"
# DFS_MOUNT_POINT="/dfs"
# DFS_CACHE_DIR="/var/dfs/cache"
SCRIPT_ROOT="$OPTDIR/SvdOpt/"
BOOT_LOADER_CONFIG="/boot/loader.conf"
DEFINITIONS_DIR="${SCRIPT_ROOT}definitions/"
DEFAULTS="${DEFINITIONS_DIR}defaults.def"
LOG="${SOFTWARE_DIR}INSTALL_LOG"
PREFILES="${SCRIPT_ROOT}prefiles/etc/"
DINSTAPP="${SCRIPT_ROOT}}SOFTWARE-INSTALLER"
SYSTEM_GET_SHELL_PATH="$DINSTAPP getshellpath"
SYSTEM_GET_SHELL_LDLIB="$DINSTAPP getshellld"
KERNELBUILDAPP="$(pwd)/GRUNT-KERNEL-BUILD"


if [ "$SYSTEM_NAME" = "Linux" ]; then
    SED_BIN="/bin/sed"
    MKTEMP_BIN="/bin/mktemp"
    TAR_BIN="/bin/tar"
    FETCH_BIN="/usr/bin/wget"
    GREP_BIN="/bin/grep"
fi

if [ "$SYSTEM_NAME" = "Darwin" ]; then
    FETCH_BIN="/usr/bin/curl --progress-bar -C - -L -O"
fi
