#!/bin/sh

. /etc/rc.subr

name="served"
pid_file="/SystemUsers/0.pid"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

served_start()
{
    echo "Starting ServeD KickStart"
    if [ -e "$pid_file" ]; then
        ps -A |grep $(cat $pid_file) > /dev/null 2>&1
        if [ "$?" = "0" ]; then
            echo "Already started!"
            exit
        else
            svdkick &
        fi
    else
        svdkick &
    fi

}

served_stop()
{
    echo "Stopping ServeD KickStart"
    if [ ! -e "$pid_file" ]; then
        echo "Already stopped!"
        exit
    else
        kill -INT "$(cat $pid_file)"
    fi
}


load_rc_config $name
run_rc_command "$1"