#!/usr/bin/env zsh

unset DEBUG TRACE

case "$(uname)" in
    Darwin)
        SOFIN_ROOT="/Users/Shared/Software/Sofin"
        TMUX_BIN="/Users/Shared/Services/Sofin/exports/tmux"
        ;;
    *)
        SOFIN_ROOT="/Software/Sofin"
        TMUX_BIN="/Services/Sofin/exports/tmux"
        ;;
esac

. "${SOFIN_ROOT}/share/loader"

permnote "Wiping out all Sofin locks, cached files and temporary files"
for _service_dir in ${SERVICES_DIR}/*; do
    _service_name="${_service_dir##${SERVICES_DIR}/}"
    case "${_service_name}" in
        Git|Zsh|Sofin)
            ;;

        *)
            permnote "Destroying ${DEFAULT_ZPOOL}${SERVICES_DIR}/root/${_service_name}"
            case "${CAP_SYS_ZFS}" in
                yes|YES)
                    try "${ZFS_BIN} set readonly=off ${DEFAULT_ZPOOL}${SERVICES_DIR}/root"
                    try "${ZFS_BIN} set readonly=off ${DEFAULT_ZPOOL}${SERVICES_DIR}/root/${_service_name}"
                    try "${ZFS_BIN} umount -f ${DEFAULT_ZPOOL}${SERVICES_DIR}/root/${_service_name}"
                    try "${ZFS_BIN} destroy -r -f ${DEFAULT_ZPOOL}${SERVICES_DIR}/root/${_service_name}"
                    ;;

                *)
                    permnote "Destroying ${_service_dir}"
                    ;;
            esac
            ${FIND_BIN} "${_service_dir}" -delete
            ;;
    esac
done

permnote "Wiping out all previously built software"
for _soft_dir in ${SOFTWARE_DIR}/*; do
    _soft_name="${_soft_dir##${SOFTWARE_DIR}/}"
    case "${_soft_name}" in
        Git|Zsh|Sofin)
            ;;

        *)
            case "${CAP_SYS_ZFS}" in
                yes|YES)
                    permnote "Destroying ${DEFAULT_ZPOOL}${SOFTWARE_DIR}/root/${_soft_name}"
                    try "${ZFS_BIN} set readonly=off ${DEFAULT_ZPOOL}${SOFTWARE_DIR}/root"
                    try "${ZFS_BIN} set readonly=off ${DEFAULT_ZPOOL}${SOFTWARE_DIR}/root/${_soft_name}"
                    try "${ZFS_BIN} umount -f ${DEFAULT_ZPOOL}${SOFTWARE_DIR}/root/${_soft_name}"
                    try "${ZFS_BIN} destroy -r -f ${DEFAULT_ZPOOL}${SOFTWARE_DIR}/root/${_soft_name}"
                    ;;

                *)
                    permnote "Destroying ${_soft_dir}"
                    ;;
            esac
            ${FIND_BIN} "${_soft_dir}" -delete
            ;;
    esac
done

permnote "Cleaning up leftovers from previous builds"

${FIND_BIN} . -type f -name '*.randomized' -or -name 'sofin-ci-*' -delete 2>/dev/null
${FIND_BIN} "/boot/kernel.old" -delete 2>/dev/null
${FIND_BIN} "/tmp" -type f -delete 2>/dev/null
${FIND_BIN} "${HOME}/.sofin/file-cache" -name '*.txz' -type f -delete 2>/dev/null
${FIND_BIN} "${HOME}/.sofin/file-cache" -name '*.sha*' -type f -delete 2>/dev/null
${FIND_BIN} "${HOME}/.sofin/locks" -type f -delete 2>/dev/null
${FIND_BIN} "/Projects" -name 'Utilities*' -type f -delete 2>/dev/null
${FIND_BIN} "${HOME}/.vifm" -delete 2>/dev/null
${FIND_BIN} "${HOME}/go" -delete 2>/dev/null
${FIND_BIN} "${HOME}/.cpan" -delete 2>/dev/null
${FIND_BIN} "${HOME}/.npm" -delete 2>/dev/null
${FIND_BIN} "${HOME}/.cargo" -delete 2>/dev/null
${FIND_BIN} "${HOME}/.cmake" -delete 2>/dev/null
${FIND_BIN} "${HOME}/.cache/go-build" -delete 2>/dev/null
${FIND_BIN} "${HOME}/.cache/node-gyp" -delete 2>/dev/null
${FIND_BIN} "${HOME}/.cache/pip" -delete 2>/dev/null


if [ ! -f "${SERVED_BUILDHOST_INDICATOR_FILE}" ]; then
    set_system_dataset_writable
    permnote "Marking current system as build host"
    ${TOUCH_BIN} "${SERVED_BUILDHOST_INDICATOR_FILE}"
    set_system_dataset_readonly
fi
