#!/usr/bin/env zsh

SOFIN_ROOT="${SOFIN_ROOT:-/Software/Sofin}"
. "${SOFIN_ROOT}/share/loader"

if [ ! -f "${SERVED_BUILDHOST_INDICATOR_FILE}" ]; then
    set_system_dataset_writable
    permnote "Marking current system as build host"
    ${TOUCH_BIN} "${SERVED_BUILDHOST_INDICATOR_FILE}"
    set_system_dataset_readonly
fi

permnote "Wiping out all Sofin locks and cached bundle files"
${RM_BIN} -f ${HOME}/.sofin/locks/*.lock ${HOME}/.sofin/file-cache/*.zfs* 2>/dev/null

case "${SYSTEM_ARCH}" in
    arm64)
        _workers="2"
        ;;

    amd64|x86_64)
        _workers="4"
        ;;
esac

_src_list="software-${SYSTEM_ARCH}.list"
_lines="$(${GREP_BIN} -c '' "${_src_list}")"
if [ "0" = "${_lines}" ]; then
    error "Empty lines in software list: $(diste "${_src_list}")!"
fi

_split_name="sofin-ci"
_split_by="$(( (${_lines} / ${_workers}) + 1 ))"

debug "workers: $(distd "${_workers}"), lines: $(distd "${_lines}"), split by: $(distd "${_split_by}") lines"
${SPLIT_BIN} -l "${_split_by}" "${_src_list}" "${_split_name}-"


permnote "Checking remote machine connection (shouldn't take more than a second).."
run "${SSH_BIN} sofin@software.verknowsys.com uname -a"

# Curl binary utlility:
_tmux="/Services/Sofin/exports/tmux"
if [ ! -x "${_tmux}" ]; then
    run "s util Tmux-util"
fi


permnote "Starting parallel build via Tmux"

${_tmux} new-session -d zsh
for _idx in $(${SEQ_BIN} 2 "${_workers}"); do
    ${_tmux} split-window -h zsh
done

case "${SYSTEM_ARCH}" in
    arm64)
        _worker="2"
        ${_tmux} send -t 0:0.0 "./build-list ${_split_name}-aa" C-m
        ${_tmux} send -t 0:0.1 "./build-list ${_split_name}-ab" C-m
        ;;

    amd64|x86_64)
        _worker="4"
        ${_tmux} send -t 0:0.0 "./build-list ${_split_name}-aa" C-m
        ${_tmux} send -t 0:0.1 "./build-list ${_split_name}-ab" C-m
        ${_tmux} send -t 0:0.2 "./build-list ${_split_name}-ac" C-m
        ${_tmux} send -t 0:0.3 "./build-list ${_split_name}-ad" C-m
        ;;
esac

${_tmux} select-layout tiled

${_tmux} -2 attach-session -d
