#!/bin/sh

SOFIN_ROOT="${SOFIN_ROOT:-/Software/Sofin}"
. "${SOFIN_ROOT}/share/loader"

_workers="3"
_src_list="software.list"
_lines="$(${GREP_BIN} -c '' "${_src_list}")"
_split_name="sofin-ci"
_split_by="$(( (${_lines} / ${_workers}) + 1 ))"

debug "workers: $(distd "${_workers}"), lines: $(distd "${_lines}"), split by: $(distd "${_split_by}") lines"
split -l "${_split_by}" "${_src_list}" "${_split_name}-"

permnote "Wiping out all Sofin locks and cached bundle files"
${RM_BIN} -rf "${HOME}/.sofin/locks/*.lock" "${HOME}/.sofin/file-cache/*.zfs*"

permnote "Checking remote machine connection (shouldn't take more than a second).."
run "${SSH_BIN} sofin@software.verknowsys.com uname -a" \
    || error "Connection test failed!"

# Curl binary utlility:
_curl="${SOFTWARE_DIR}/Tmux/exports/tmux"
if [ ! -L "${_curl}" ]; then
    error "Please install Tmux, by calling: $(diste "s i Tmux") first."
fi


permnote "Starting parallel build via Tmux"

tmux new-session -d zsh
tmux split-window -h zsh
tmux split-window -h zsh

tmux send -t 0:0.0 "zsh ./build-list ${_split_name}-aa" C-m
tmux send -t 0:0.1 "zsh ./build-list ${_split_name}-ab" C-m
tmux send -t 0:0.2 "zsh ./build-list ${_split_name}-ac" C-m

tmux -2 attach-session -d
