# Created by newuser for 4.3.10
autoload colors zsh/terminfo
colors

#Completion online
autoload -U compinit
compinit

#ZSH completion caching
#ie, cache things so they show up faster next time
zstyle ':completion:*' use-cache on 
zstyle ':completion:*' cache-path ~/.zsh/cache

#if colordiff is installed, prefer it
if [[ -x /usr/bin/colordiff || -x /usr/local/bin/colordiff ]]; then
	alias diff='colordiff' 
fi

setprompt () {
    # Need this, so the prompt will work
    setopt prompt_subst

    for COLOR in RED GREEN YELLOW WHITE BLACK BLUE CYAN MAGENTA; do
        eval PR_$COLOR='%{$fg[${(L)COLOR}]%}'
        eval PR_BRIGHT_$COLOR='%{$fg_bold[${(L)COLOR}]%}'
    done

    PR_RESET="%{$reset_color%}"

    # Finally, let's set the prompt
    if [ `id -u` -eq "0" ]; then
      	PS1='${PR_RED}%m ${PR_YELLOW}%$PR_PWDLEN<...<%~% ${PR_RESET} %# '
    else
    	PS1='${PR_GREEN}%m ${PR_YELLOW}%$PR_PWDLEN<...<%~% ${PR_RESET} %% '
    fi
}

setprompt

export LSCOLORS=cxfxcxdxbxegedabagacad

setopt share_history
setopt appendhistory
setopt autocd
setopt automenu
setopt autopushd
setopt autoresume
setopt complete_in_word
setopt extended_glob
setopt hist_ignoredups
setopt hist_ignorespace
setopt list_types
setopt mailwarning
setopt no_flowcontrol
setopt no_hup
setopt no_notify
setopt printexitvalue
setopt pushd_ignoredups
setopt pushd_silent

export HISTFILE=$HOME/.zsh_history
export HISTSIZE=8192
export SAVEHIST=8192

export HISTCONTROL=erasedups
export HISTSIZE=10000
setopt histappend

# zgitinit and prompt_wunjo_setup must be somewhere in your $fpath, see README for more.

setopt promptsubst

# Load the prompt theme system
autoload -U promptinit
promptinit

export LANGUAGE="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export TERM=xterm-color
export PAGER=less
export JAVA_OPTS=" -XX:MaxPermSize=512m -XX:+UseCompressedOops -XX:+UseParallelGC -XX:+UseParallelOldGC -Xms128m -Xmx768m -Dfile.encoding=UTF-8 -noverify -server"

alias top='top -a -i -u -S -ores'
alias ls='ls -G'
alias grep='grep --color=auto'
alias w="w -din"
alias screen='screen -U'
alias pstree='pstree -g 3'

ulimit -c 0
. /etc/profile
